// models/seed.js

const { sequelize, Exercise } = require('./index');

const seedExercises = async () => {
    try {
        const exercisesData = [
            {
                name: 'Bench Press',
                equipment: 'Barbell',
                muscle: 'Chest, Tricep, Shoulders',
                image: '',
                how: 'Berbaringlah di bangku datar dengan kaki di tanah. Pegang barbell dengan tangan selebar bahu. Turunkan barbell ke dada, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Bench Press',
                equipment: 'Dumbbell',
                muscle: 'Chest, Tricep, Shoulders',
                image: '',
                how: 'Berbaringlah di bangku datar dengan kaki di tanah. Pegang dumbbell di masing-masing tangan dengan posisi lengan lurus di atas dada. Turunkan dumbbell ke samping dada, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Chest Fly',
                equipment: 'Dumbbell',
                muscle: 'Chest, Shoulders',
                image: '',
                how: 'Berbaringlah di bangku datar dengan dumbbell di tangan. Angkat lengan ke atas dengan sedikit tekuk di siku. Buka lengan ke samping hingga dada terasa terentang, kemudian kembali ke posisi awal.',
            },
            {
                name: 'Chest Fly',
                equipment: 'Cable',
                muscle: 'Chest, Shoulders',
                image: '',
                how: 'Atur kabel di mesin ke posisi atas. Pegang pegangan dengan kedua tangan dan tarik kedua tangan ke depan hingga tangan bertemu di tengah. Kembali perlahan ke posisi awal.',
            },
            {
                name: 'Push Up',
                equipment: 'None',
                muscle: 'Chest, Tricep, Shoulders',
                image: '',
                how: 'Mulailah dalam posisi plank dengan tangan sedikit lebih lebar dari bahu. Turunkan tubuh hingga dada hampir menyentuh lantai. Dorong kembali ke posisi awal.',
            },
            {
                name: 'Deadlift',
                equipment: 'Barbell',
                muscle: 'Back, Legs, Forearm',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan barbell di depan. Tekuk lutut dan dorong pinggul ke belakang untuk mengambil barbell. Angkat barbell hingga berdiri tegak, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Pull Up',
                equipment: 'None',
                muscle: 'Back, Bicep, Forearm',
                image: '',
                how: 'Gantungkan diri pada bar dengan tangan selebar bahu. Tarik tubuh ke atas hingga dagu melewati bar, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Bent Over Row',
                equipment: 'Barbell',
                muscle: 'Back, Bicep, Shoulders',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan sedikit tekuk lutut. Condongkan tubuh ke depan dengan punggung lurus. Pegang barbell dengan tangan selebar bahu dan tarik ke arah perut, kemudian turunkan kembali.',
            },
            {
                name: 'Bent Over Row',
                equipment: 'Dumbbell',
                muscle: 'Back, Bicep, Shoulders',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan sedikit tekuk lutut. Condongkan tubuh ke depan dengan punggung lurus. Pegang dumbbell di masing-masing tangan dan tarik ke arah perut, kemudian turunkan kembali.',
            },
            {
                name: 'Shoulder Press',
                equipment: 'Barbell',
                muscle: 'Shoulders, Tricep',
                image: '',
                how: 'Duduk atau berdiri dengan barbell di atas bahu. Dorong barbell ke atas hingga lengan lurus, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Shoulder Press',
                equipment: 'Dumbbell',
                muscle: 'Shoulders, Tricep',
                image: '',
                how: 'Duduk atau berdiri dengan dumbbell di masing-masing tangan di bahu. Dorong dumbbell ke atas hingga lengan lurus, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Lateral Raise',
                equipment: 'Dumbbell',
                muscle: 'Shoulders',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan di sisi tubuh. Angkat lengan ke samping hingga sejajar dengan lantai, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Front Raise',
                equipment: 'Dumbbell',
                muscle: 'Shoulders',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan di depan paha. Angkat lengan lurus ke depan hingga sejajar dengan lantai, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Biceps Curl',
                equipment: 'Dumbbell',
                muscle: 'Bicep, Forearm',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan, telapak tangan menghadap ke depan. Angkat dumbbell ke arah bahu dengan menekuk siku, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Biceps Curl',
                equipment: 'Barbell',
                muscle: 'Bicep, Forearm',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan pegang barbell dengan tangan selebar bahu. Angkat barbell ke arah bahu dengan menekuk siku, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Triceps Extension',
                equipment: 'Dumbbell',
                muscle: 'Tricep, Shoulders',
                image: '',
                how: 'Duduk atau berdiri dengan dumbbell di tangan. Angkat dumbbell ke atas kepala dengan lengan lurus, kemudian tekuk siku untuk menurunkan dumbbell di belakang kepala. Luruskan kembali lengan.',
            },
            {
                name: 'Triceps Extension',
                equipment: 'Cable',
                muscle: 'Tricep, Shoulders',
                image: '',
                how: 'Pegang pegangan kabel dengan kedua tangan. Dorong pegangan ke bawah hingga lengan lurus, kemudian tarik kembali ke posisi awal dengan menekuk siku.',
            },
            {
                name: 'Squat',
                equipment: 'Barbell',
                muscle: 'Legs, Glutes, Lower Back',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan barbell di punggung. Turunkan tubuh dengan menekuk lutut dan pinggul seolah duduk di kursi, kemudian dorong kembali ke posisi berdiri.',
            },
            {
                name: 'Squat',
                equipment: 'Dumbbell',
                muscle: 'Legs, Glutes, Lower Back',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan pegang dumbbell di sisi tubuh atau di bahu. Turunkan tubuh dengan menekuk lutut dan pinggul, kemudian dorong kembali ke posisi berdiri.',
            },
            {
                name: 'Squat',
                equipment: 'None',
                muscle: 'Legs, Glutes, Lower Back',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu. Turunkan tubuh dengan menekuk lutut dan pinggul seolah duduk di kursi, kemudian dorong kembali ke posisi berdiri.',
            },
            {
                name: 'Lunges',
                equipment: 'Barbell',
                muscle: 'Legs, Glutes, Hamstrings',
                image: '',
                how: 'Berdiri dengan barbell di punggung. Langkahkan satu kaki ke depan dan turunkan tubuh hingga kedua lutut membentuk sudut 90 derajat. Dorong kembali ke posisi awal dan ganti kaki.',
            },
            {
                name: 'Lunges',
                equipment: 'Dumbbell',
                muscle: 'Legs, Glutes, Hamstrings',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan. Langkahkan satu kaki ke depan dan turunkan tubuh hingga kedua lutut membentuk sudut 90 derajat. Dorong kembali ke posisi awal dan ganti kaki.',
            },
            {
                name: 'Lunges',
                equipment: 'None',
                muscle: 'Legs, Glutes, Hamstrings',
                image: '',
                how: 'Berdiri tegak. Langkahkan satu kaki ke depan dan turunkan tubuh hingga kedua lutut membentuk sudut 90 derajat. Dorong kembali ke posisi awal dan ganti kaki.',
            },
            {
                name: 'Leg Press',
                equipment: 'Machine',
                muscle: 'Legs, Glutes, Hamstrings',
                image: '',
                how: 'Duduk di mesin leg press dengan kaki di platform. Dorong platform dengan kaki hingga kaki lurus, kemudian turunkan kembali dengan menekuk lutut.',
            },
            {
                name: 'Calf Raise',
                equipment: 'Dumbbell',
                muscle: 'Calves',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan atau di bahu. Angkat tumit hingga berdiri di atas jari kaki, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Calf Raise',
                equipment: 'Barbell',
                muscle: 'Calves',
                image: '',
                how: 'Berdiri dengan barbell di punggung. Angkat tumit hingga berdiri di atas jari kaki, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Plank',
                equipment: 'None',
                muscle: 'Abs, Core, Shoulders',
                image: '',
                how: 'Mulailah dalam posisi push-up namun dengan berat badan ditopang pada lengan bawah. Tahan posisi ini dengan punggung lurus dan perut kencang selama waktu yang ditentukan.',
            },
            {
                name: 'Russian Twist',
                equipment: 'Medicine Ball',
                muscle: 'Abs, Obliques',
                image: '',
                how: 'Duduk dengan lutut ditekuk dan kaki diangkat sedikit. Pegang medicine ball di tangan dan putar tubuh ke kanan dan kiri secara bergantian.',
            },
            {
                name: 'Russian Twist',
                equipment: 'Dumbbell',
                muscle: 'Abs, Obliques',
                image: '',
                how: 'Duduk dengan lutut ditekuk dan kaki diangkat sedikit. Pegang dumbbell di tangan dan putar tubuh ke kanan dan kiri secara bergantian.',
            },
            {
                name: 'Burpees',
                equipment: 'None',
                muscle: 'Full Body, Cardio',
                image: '',
                how: 'Mulailah dalam posisi berdiri. Turunkan ke posisi squat, letakkan tangan di lantai dan lompatkan kaki ke belakang ke posisi plank. Lakukan push-up, lompatkan kaki kembali ke posisi squat, lalu lompat ke udara dengan tangan di atas kepala.',
            },
            {
                name: 'Kettlebell Swing',
                equipment: 'Kettlebell',
                muscle: 'Full Body, Glutes, Hamstrings, Shoulders',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan pegang kettlebell dengan kedua tangan di antara kaki. Ayunkan kettlebell ke antara kaki dengan menekuk lutut sedikit, kemudian ayunkan ke depan setinggi dada dengan menggerakkan pinggul ke depan dan luruskan tubuh.',
            },
            {
                name: 'Hip Thrust',
                equipment: 'Barbell',
                muscle: 'Glutes, Hamstrings, Lower Back',
                image: '',
                how: 'Duduk di lantai dengan punggung bersandar pada bangku. Letakkan barbell di pinggul dan dorong pinggul ke atas hingga tubuh sejajar dengan lantai, lalu turunkan kembali ke posisi awal.',
            },
            {
                name: 'Dead Bug',
                equipment: 'None',
                muscle: 'Abs, Core',
                image: '',
                how: 'Berbaring telentang dengan tangan lurus ke atas dan lutut ditekuk 90 derajat. Turunkan lengan kanan dan kaki kiri secara bersamaan tanpa menyentuh lantai, kemudian kembali ke posisi awal dan ganti sisi.',
            },
            {
                name: 'Leg Curl',
                equipment: 'Machine',
                muscle: 'Hamstrings',
                image: '',
                how: 'Berbaring di mesin leg curl dengan tumit di bawah bantalan. Tekuk lutut untuk menarik bantalan ke arah bokong, lalu luruskan kembali kaki.',
            },
            {
                name: 'Leg Extension',
                equipment: 'Machine',
                muscle: 'Quadriceps',
                image: '',
                how: 'Duduk di mesin leg extension dengan kaki di bawah bantalan. Luruskan kaki hingga lurus, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Glute Bridge',
                equipment: 'None',
                muscle: 'Glutes, Hamstrings, Lower Back',
                image: '',
                how: 'Berbaring telentang dengan lutut ditekuk dan kaki di lantai. Angkat pinggul ke atas hingga tubuh membentuk garis lurus dari bahu ke lutut, lalu turunkan kembali ke posisi awal.',
            },
            {
                name: 'Mountain Climber',
                equipment: 'None',
                muscle: 'Full Body, Core, Cardio',
                image: '',
                how: 'Mulailah dalam posisi plank. Angkat satu lutut ke arah dada, lalu ganti dengan lutut lainnya secara bergantian dengan cepat.',
            },
            {
                name: 'Jump Rope',
                equipment: 'Jump Rope',
                muscle: 'Full Body, Cardio, Legs',
                image: '',
                how: 'Pegang tali skipping di masing-masing tangan. Ayunkan tali melewati kepala dan lompat saat tali menyentuh lantai, ulangi dengan ritme yang konsisten.',
            },
            {
                name: 'Overhead Triceps Extension',
                equipment: 'Dumbbell',
                muscle: 'Tricep, Shoulders',
                image: '',
                how: 'Duduk atau berdiri dengan dumbbell di tangan. Angkat dumbbell ke atas kepala dengan lengan lurus, kemudian tekuk siku untuk menurunkan dumbbell di belakang kepala. Luruskan kembali lengan.',
            },
            {
                name: 'Hammer Curl',
                equipment: 'Dumbbell',
                muscle: 'Bicep, Forearm',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan dengan telapak tangan menghadap ke dalam. Angkat dumbbell ke arah bahu dengan menekuk siku, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Concentration Curl',
                equipment: 'Dumbbell',
                muscle: 'Bicep',
                image: '',
                how: 'Duduk di bangku dengan kaki terbuka. Pegang dumbbell di salah satu tangan dan letakkan siku di dalam paha. Angkat dumbbell ke arah bahu dengan menekuk siku, kemudian turunkan kembali.',
            },
            {
                name: 'Lat Pulldown',
                equipment: 'Machine',
                muscle: 'Back, Bicep, Shoulders',
                image: '',
                how: 'Duduk di mesin lat pulldown dan pegang bar dengan tangan selebar bahu. Tarik bar ke bawah hingga menyentuh dada, kemudian angkat kembali ke posisi awal.',
            },
            {
                name: 'Seated Row',
                equipment: 'Machine',
                muscle: 'Back, Bicep, Shoulders',
                image: '',
                how: 'Duduk di mesin seated row dengan kaki di depan. Pegang pegangan dan tarik ke arah tubuh dengan menekuk siku, kemudian luruskan kembali lengan.',
            },
            {
                name: 'Face Pull',
                equipment: 'Cable',
                muscle: 'Shoulders, Upper Back, Trapezius',
                image: '',
                how: 'Pasang tali di mesin kabel pada tinggi wajah. Pegang tali dengan kedua tangan dan tarik ke arah wajah sambil menyebarkan tangan, kemudian kembali ke posisi awal.',
            },
            {
                name: 'Upright Row',
                equipment: 'Barbell',
                muscle: 'Shoulders, Trapezius, Bicep',
                image: '',
                how: 'Berdiri dengan barbell di depan paha. Angkat barbell ke atas hingga setinggi dada dengan menekuk siku ke samping, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Upright Row',
                equipment: 'Dumbbell',
                muscle: 'Shoulders, Trapezius, Bicep',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan di depan paha. Angkat dumbbell ke atas hingga setinggi dada dengan menekuk siku ke samping, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Goblet Squat',
                equipment: 'Kettlebell',
                muscle: 'Legs, Glutes, Core',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan pegang kettlebell di depan dada dengan kedua tangan. Turunkan tubuh ke posisi squat dengan menekuk lutut dan pinggul, kemudian dorong kembali ke posisi berdiri.',
            },
            {
                name: 'Front Squat',
                equipment: 'Barbell',
                muscle: 'Legs, Glutes, Core',
                image: '',
                how: 'Berdiri dengan barbell di depan bahu dengan siku ditekuk ke atas. Turunkan tubuh ke posisi squat dengan menekuk lutut dan pinggul, kemudian dorong kembali ke posisi berdiri.',
            },
            {
                name: 'Sumo Deadlift',
                equipment: 'Barbell',
                muscle: 'Legs, Glutes, Back',
                image: '',
                how: 'Berdiri dengan kaki lebih lebar dari bahu dan jari kaki mengarah ke luar. Pegang barbell dengan tangan di dalam posisi kaki. Angkat barbell dengan menekuk lutut dan pinggul, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Single-Leg Deadlift',
                equipment: 'Dumbbell',
                muscle: 'Hamstrings, Glutes, Core',
                image: '',
                how: 'Berdiri dengan satu kaki diangkat sedikit di belakang. Pegang dumbbell di satu tangan dan turunkan dumbbell ke arah lantai sambil menjaga punggung tetap lurus. Kembali ke posisi awal dan ganti kaki.',
            },
            {
                name: 'T-Bar Row',
                equipment: 'Barbell',
                muscle: 'Back, Bicep, Shoulders',
                image: '',
                how: 'Berdiri di ujung barbell yang dimodifikasi dengan pegangan. Condongkan tubuh ke depan dengan punggung lurus dan tarik barbell ke arah dada, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Incline Bench Press',
                equipment: 'Barbell',
                muscle: 'Upper Chest, Shoulders, Tricep',
                image: '',
                how: 'Berbaring di bangku incline dengan kaki di tanah. Pegang barbell dengan tangan selebar bahu. Turunkan barbell ke dada bagian atas, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Incline Bench Press',
                equipment: 'Dumbbell',
                muscle: 'Upper Chest, Shoulders, Tricep',
                image: '',
                how: 'Berbaring di bangku incline dengan dumbbell di masing-masing tangan. Turunkan dumbbell ke dada bagian atas, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Decline Bench Press',
                equipment: 'Barbell',
                muscle: 'Lower Chest, Shoulders, Tricep',
                image: '',
                how: 'Berbaring di bangku decline dengan kaki di atas. Pegang barbell dengan tangan selebar bahu. Turunkan barbell ke dada bagian bawah, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Decline Bench Press',
                equipment: 'Dumbbell',
                muscle: 'Lower Chest, Shoulders, Tricep',
                image: '',
                how: 'Berbaring di bangku decline dengan dumbbell di masing-masing tangan. Turunkan dumbbell ke dada bagian bawah, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Shrug',
                equipment: 'Barbell',
                muscle: 'Trapezius, Shoulders',
                image: '',
                how: 'Berdiri dengan barbell di tangan dan kaki selebar bahu. Angkat bahu ke arah telinga dengan menarik barbell, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Shrug',
                equipment: 'Dumbbell',
                muscle: 'Trapezius, Shoulders',
                image: '',
                how: 'Berdiri dengan dumbbell di masing-masing tangan. Angkat bahu ke arah telinga dengan menarik dumbbell, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Leg Raise',
                equipment: 'None',
                muscle: 'Abs, Hip Flexors',
                image: '',
                how: 'Berbaring telentang dengan tangan di samping tubuh. Angkat kedua kaki lurus ke atas hingga membentuk sudut 90 derajat dengan tubuh, kemudian turunkan kembali tanpa menyentuh lantai.',
            },
            {
                name: 'Bicycle Crunch',
                equipment: 'None',
                muscle: 'Abs, Obliques',
                image: '',
                how: 'Berbaring telentang dengan tangan di belakang kepala. Angkat lutut ke posisi 90 derajat dan lakukan gerakan seperti mengayuh sepeda sambil menyentuh siku ke lutut yang berlawanan.',
            },
            {
                name: 'Hanging Leg Raise',
                equipment: 'Pull Up Bar',
                muscle: 'Abs, Hip Flexors',
                image: '',
                how: 'Gantung di pull up bar dengan tangan selebar bahu. Angkat kedua kaki lurus ke depan hingga sejajar dengan lantai, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'Side Plank',
                equipment: 'None',
                muscle: 'Abs, Obliques, Core',
                image: '',
                how: 'Berbaring miring dengan siku di bawah bahu. Angkat pinggul hingga tubuh membentuk garis lurus dari kepala hingga kaki. Tahan posisi ini selama waktu yang ditentukan, kemudian ganti sisi.',
            },
            {
                name: 'Flutter Kick',
                equipment: 'None',
                muscle: 'Abs, Hip Flexors',
                image: '',
                how: 'Berbaring telentang dengan tangan di bawah bokong. Angkat kaki sedikit dari lantai dan lakukan gerakan kaki naik turun secara bergantian seperti gerakan berenang.',
            },
            {
                name: 'Windmill',
                equipment: 'Dumbbell',
                muscle: 'Shoulders, Obliques, Hamstrings',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan dumbbell di salah satu tangan di atas kepala. Condongkan tubuh ke samping sambil mengangkat kaki yang berlawanan ke belakang, kemudian kembali ke posisi awal dan ganti sisi.',
            },
            {
                name: 'Renegade Row',
                equipment: 'Dumbbell',
                muscle: 'Back, Bicep, Core, Shoulders',
                image: '',
                how: 'Mulailah dalam posisi plank dengan dumbbell di masing-masing tangan. Tarik salah satu dumbbell ke arah pinggang sambil menjaga tubuh tetap stabil, kemudian turunkan kembali dan ganti sisi.',
            },
            {
                name: 'Thruster',
                equipment: 'Barbell',
                muscle: 'Full Body, Legs, Shoulders, Core',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan barbell di depan bahu. Turunkan tubuh ke posisi squat, lalu dorong barbell ke atas saat berdiri kembali.',
            },
            {
                name: 'Thruster',
                equipment: 'Dumbbell',
                muscle: 'Full Body, Legs, Shoulders, Core',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu dan dumbbell di masing-masing tangan di depan bahu. Turunkan tubuh ke posisi squat, lalu dorong dumbbell ke atas saat berdiri kembali.',
            },
            {
                name: 'Farmer\'s Walk',
                equipment: 'Dumbbell',
                muscle: 'Full Body, Grip, Core',
                image: '',
                how: 'Pegang dumbbell berat di masing-masing tangan. Berjalan sejauh yang ditentukan dengan tubuh tegak dan perut kencang.',
            },
            {
                name: 'Battle Ropes',
                equipment: 'Battle Ropes',
                muscle: 'Full Body, Arms, Core, Cardio',
                image: '',
                how: 'Pegang ujung battle ropes di masing-masing tangan. Lakukan gelombang dengan menggerakkan lengan ke atas dan ke bawah secara bergantian atau simultan selama waktu yang ditentukan.',
            },
            {
                name: 'Medicine Ball Slam',
                equipment: 'Medicine Ball',
                muscle: 'Full Body, Core, Shoulders',
                image: '',
                how: 'Angkat medicine ball ke atas kepala, kemudian lemparkan ke lantai dengan tenaga penuh sambil membungkuk ke depan. Ambil kembali medicine ball dan ulangi.',
            },
            {
                name: 'Cable Woodchopper',
                equipment: 'Cable',
                muscle: 'Obliques, Core, Shoulders',
                image: '',
                how: 'Atur kabel di mesin ke posisi atas atau bawah. Pegang pegangan dengan kedua tangan dan putar tubuh ke samping sambil menarik kabel ke bawah atau ke atas, kemudian kembali ke posisi awal dan ganti sisi.',
            },
            {
                name: 'Pistol Squat',
                equipment: 'None',
                muscle: 'Legs, Glutes, Core',
                image: '',
                how: 'Berdiri dengan satu kaki dan angkat kaki lainnya lurus di depan. Turunkan tubuh ke posisi squat dengan kaki yang berdiri, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Box Jump',
                equipment: 'Box',
                muscle: 'Legs, Glutes, Core',
                image: '',
                how: 'Berdiri di depan box atau platform. Lompat ke atas box dengan kedua kaki dan mendarat dengan kaki selebar bahu. Turun kembali ke posisi awal dan ulangi.',
            },
            {
                name: 'TRX Row',
                equipment: 'TRX',
                muscle: 'Back, Bicep, Core',
                image: '',
                how: 'Pegang TRX dengan kedua tangan dan condongkan tubuh ke belakang dengan kaki lurus. Tarik tubuh ke arah TRX dengan menekuk siku, kemudian turunkan kembali ke posisi awal.',
            },
            {
                name: 'TRX Push-Up',
                equipment: 'TRX',
                muscle: 'Chest, Tricep, Shoulders, Core',
                image: '',
                how: 'Pegang TRX dengan kedua tangan dan posisikan tubuh dalam posisi push-up. Turunkan tubuh dengan menekuk siku, lalu dorong kembali ke posisi awal.',
            },
            {
                name: 'Single-Arm Dumbbell Press',
                equipment: 'Dumbbell',
                muscle: 'Chest, Shoulders, Tricep, Core',
                image: '',
                how: 'Berbaring di bangku dengan satu dumbbell di tangan. Angkat dumbbell ke atas dengan lengan lurus, kemudian turunkan kembali ke posisi awal. Ulangi dengan sisi lainnya.',
            },
            {
                name: 'Single-Leg Glute Bridge',
                equipment: 'None',
                muscle: 'Glutes, Hamstrings, Core',
                image: '',
                how: 'Berbaring telentang dengan satu kaki diangkat ke udara dan lutut ditekuk. Angkat pinggul ke atas dengan kaki yang tetap di lantai, lalu turunkan kembali ke posisi awal. Ulangi dengan kaki lainnya.',
            },
            {
                name: 'Kettlebell Clean and Press',
                equipment: 'Kettlebell',
                muscle: 'Full Body, Shoulders, Legs, Core',
                image: '',
                how: 'Angkat kettlebell dari lantai ke posisi rack di bahu dengan satu gerakan cepat, kemudian dorong kettlebell ke atas kepala hingga lengan lurus. Turunkan kembali ke posisi rack dan kemudian ke lantai.',
            },
            {
                name: 'Dips',
                equipment: 'Dip Bar',
                muscle: 'Tricep, Chest, Shoulders',
                image: '',
                how: 'Genggam dip bar dan angkat tubuh hingga lengan lurus. Turunkan tubuh dengan menekuk siku hingga siku membentuk sudut 90 derajat, kemudian dorong kembali ke posisi awal.',
            },
            {
                name: 'Cable Kickback',
                equipment: 'Cable',
                muscle: 'Tricep',
                image: '',
                how: 'Pasang pegangan di mesin kabel. Berdiri dengan satu kaki di depan dan pegang pegangan dengan tangan yang berlawanan. Dorong lengan ke belakang hingga lurus, kemudian kembali ke posisi awal.',
            },
            {
                name: 'Bulgarian Split Squat',
                equipment: 'Dumbbell',
                muscle: 'Legs, Glutes, Hamstrings',
                image: '',
                how: 'Berdiri dengan satu kaki di depan dan kaki lainnya di atas bangku di belakang. Turunkan tubuh dengan menekuk lutut depan hingga paha sejajar dengan lantai, kemudian dorong kembali ke posisi awal. Ulangi dengan kaki lainnya.',
            },
            {
                name: 'Farmer\'s Walk',
                equipment: 'Barbell',
                muscle: 'Full Body, Grip, Core',
                image: '',
                how: 'Pegang barbell di kedua tangan dengan berat yang sesuai. Berjalan sejauh yang ditentukan dengan tubuh tegak dan perut kencang.',
            },
            {
                name: 'Sled Push',
                equipment: 'Sled',
                muscle: 'Full Body, Legs, Core, Shoulders',
                image: '',
                how: 'Pegang tali sled dan dorong sled ke depan sejauh yang ditentukan dengan langkah pendek dan cepat, sambil menjaga tubuh tegak dan perut kencang.',
            },
            {
                name: 'Sled Pull',
                equipment: 'Sled',
                muscle: 'Full Body, Legs, Core, Back',
                image: '',
                how: 'Pasang tali pada sled dan tarik sled ke arah yang ditentukan dengan langkah kuat dan stabil, menjaga tubuh tetap tegak dan punggung lurus.',
            },
            {
                name: 'Jump Squat',
                equipment: 'None',
                muscle: 'Legs, Glutes, Cardio',
                image: '',
                how: 'Berdiri dengan kaki selebar bahu. Turunkan tubuh ke posisi squat, kemudian lompat ke udara dengan tenaga penuh. Mendarat kembali ke posisi squat dan ulangi.',
            },
            {
                name: 'Plyometric Push-Up',
                equipment: 'None',
                muscle: 'Chest, Tricep, Shoulders, Core',
                image: '',
                how: 'Mulailah dalam posisi push-up. Dorong tubuh ke atas dengan tenaga penuh sehingga tangan terangkat dari lantai, kemudian mendarat kembali ke posisi push-up dan ulangi.',
            },
            {
                name: 'Bear Crawl',
                equipment: 'None',
                muscle: 'Full Body, Core, Shoulders, Legs',
                image: '',
                how: 'Mulailah dalam posisi merangkak dengan lutut sedikit diangkat dari lantai. Gerakkan tangan dan kaki secara bergantian maju sejauh yang ditentukan.',
            },
            {
                name: 'Medicine Ball Chest Pass',
                equipment: 'Medicine Ball',
                muscle: 'Chest, Shoulders, Tricep',
                image: '',
                how: 'Berdiri menghadap ke depan dengan medicine ball di dada. Dorong medicine ball ke depan dengan tenaga penuh hingga tangan lurus, kemudian tangkap kembali dan ulangi.',
            },
            {
                name: 'Battle Rope Alternating Waves',
                equipment: 'Battle Ropes',
                muscle: 'Arms, Shoulders, Core, Cardio',
                image: '',
                how: 'Pegang ujung battle ropes di masing-masing tangan. Buat gelombang bergantian dengan menggerakkan lengan ke atas dan ke bawah secara bergantian dengan cepat.',
            },
            {
                name: 'Single-Arm Kettlebell Swing',
                equipment: 'Kettlebell',
                muscle: 'Full Body, Glutes, Hamstrings, Shoulders',
                image: '',
                how: 'Pegang kettlebell dengan satu tangan di antara kaki. Ayunkan kettlebell ke antara kaki dengan menekuk lutut sedikit, kemudian ayunkan ke depan setinggi dada dengan menggerakkan pinggul ke depan dan luruskan tubuh. Ulangi dan ganti tangan.',
            },
            {
                name: 'Turkish Get-Up',
                equipment: 'Kettlebell',
                muscle: 'Full Body, Core, Shoulders',
                image: '',
                how: 'Berbaring telentang dengan kettlebell di satu tangan, lengan lurus ke atas. Bangkit ke posisi berdiri dengan menjaga kettlebell tetap di atas tangan, lalu kembali ke posisi awal dengan kontrol.',
            },
        ];

        module.exports = exercisesData;


        await sequelize.sync();

        const count = await Exercise.count();
        if (count === 0) {
            await Exercise.bulkCreate(exercisesData);
            console.log('Seeder berhasil dijalankan: Data exercises telah ditambahkan.');
        } else {
            console.log('Seeder diabaikan: Terdapat data exercises di database.');
        }

        process.exit(0);
    } catch (error) {
        console.error('Gagal menjalankan seeder:', error);
        process.exit(1);
    }
};

seedExercises();
